sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  include:
    - php: 5.5
      dist: trusty
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini

script:
  - cd extension/php$(echo $TRAVIS_PHP_VERSION | cut -b 1)/
  - phpize
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 make test
  - cd ../../analyzer
  - composer install
  - vendor/bin/phpspec run
