name: Build the extension and test the analyzers

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
#        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0']
        php-versions: ['8.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get install php${{ matrix.php-versions }}-cli php${{ matrix.php-versions }}-dev

      - name: Build the extension
        run: |
          cd extension/
          phpize
          ./configure
          make

      - name: Test the extension (PHP 7)
        if: matrix.php-versions != '8.0'
        run: |
          cd extension/
          sudo apt-get install php${{ matrix.php-versions }}-json
          REPORT_EXIT_STATUS=1 NO_INTERACTION=1 TEST_PHP_EXECUTABLE=$(which php) $(which php) run-tests.php -d extension=$PWD/modules/meminfo.so

      - name: Test the extension (PHP 8)
        if: matrix.php-versions == '8.0'
        run: |
          cd extension/
          REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ext-tests-output
          path: 'extension/tests/*.out'

      - name: Test the analyzers
        run: |
          cd analyzer
          composer install
          vendor/bin/phpspec run
